version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - ./dist:/usr/local/data/dist
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000 
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    restart: on-failure:5

volumes:
  mongo:
