version: '3'

services:
  nginx:
    profiles:
      - production
    image: nginx
    ports:
      - 80:80
     #  - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./conf.d:/etc/nginx/conf.d 
      - ./dist:/usr/local/data/dist
  backend:
    profiles:
      - production
      - debug
    ports:
      - 8000:8000
      - 27017:27017
    build:
      context: ./backend
      dockerfile: Dockerfile 
    env_file:
      - path: ./backend/.env
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000 
    restart: on-failure:5
